services:
  - type: web
    name: cosmos-launchpad-api
    env: node
    plan: starter
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 8080
      - key: CORS_ORIGINS
        sync: false
      - key: DEPLOY_RATE_LIMIT
        value: 3
      - key: GENERAL_RATE_LIMIT
        value: 100
